### ISSUE TITLE
Exclude some targets from proxying and connect them directly

### ISSUE THREAD

**Issue by Rancbar** [mezantrop/ts-warp#8]
Are there any options to exclude some targets (Domain, IP range, etc...) from going through the proxies?

I don't know maybe by defining excluded_target_domain=XXX or something like the below:

[DIRECT]
proxy_type=direct
target_domain=domain.com

**Comment by mezantrop** [comment]
Hello @Rancbar, TS-Warp pretends to be transparent, so it sticks to the open-policy: whatever is not defined in a [SECTION] to go via any proxy, goes directly. E.g., to allow domain.com in the sample config edit ts-warp.pf.conf as follows:

```
table <TSWARP> { \
    10.0.10.0/16, !10.0.12.1, \
    192.168.1.0/24, 192.168.3.0/24, !192.168.1.237, \
    123.45.123.0/24, 123.45.234.96/24, !123.45.1.11 \
    domain.com \
}

rdr pass log on lo0 inet proto tcp from any to { <TSWARP> } -> 127.0.0.1 port 10800
pass out on !lo0 route-to lo0 inet proto tcp from any to { <TSWARP> } keep state user YOURUSERNAMEHERE
```

The other story, if you use `GUI-Warp` (or `ts-warp_autofw.sh` directly) which doesn't know how to deal nor with domains nor with such exceptions. In this case, [DIRECT] could be a good idea. I'll think, thank you very much.

**Comment by mezantrop** [comment]
Ok, GUI-Warp and/or `ts-warp_autofw.sh` [takes care of domains now](https://github.com/mezantrop/ts-warp/commit/fff58d66588164db00ccf683cbd8f14f13a277d9). So, it would be possible to set in the very beginning (before the very first `[SECTION]` definition) of `ts-warp.ini`:

```
target_domain = google.com
target_domain = domain.com

[HOME NETWORK]          ; Section definition allows LeTtErS, numbers, - and _
; target_host = 192.168.1.1
; target_host = Anvil
target_domain = balmora.lan
```

GUI-Warp (and/or `ts-warp_autofw.sh`) will add all domains into `ts-warp_pf.conf` correctly:

```
table <TSWARP> { \
192.168.1.0/24, 192.168.1.0/24, \
\
google.com, domain.com, balmora.lan, \
!192.168.1.237 \
}

rdr pass log on lo0 inet proto tcp from any to { <TSWARP> } -> 127.0.0.1 port 10800
pass out on !lo0 route-to lo0 inet proto tcp from any to { <TSWARP> } keep state user YOURUSERNAMEHERE
```

When restarting ts-warp, for each `target_domain` that is defined out of the first `[SECTION]` warnings will appear in the log:

```
2024.04.06 12:40:19 WARN [2720]:        LN: 1 IGNORED: The variable is not in a section
2024.04.06 12:40:19 WARN [2720]:        LN: 2 IGNORED: The variable is not in a section
```

The out of [SECTION] domains are ignored by ts-warp, but are processed by firewall, so that's what is needed. @Rancbar, thank you again.

**Comment by Rancbar** [comment]
Thank you @mezantrop for your efforts, I'm happy that you liked the idea
I use this application frequently in my daily routine and this ability is very useful for me.
Currently, I'm not able to build the project and I will wait for your released binaries.

**Comment by mezantrop** [comment]
Thank you for the warm words? Btw, do you use it on Mac?

**Comment by Rancbar** [comment]
You're welcome, And yes I use it on Mac
